version: '3.8'

services:
  python:
    build:
      dockerfile: dockerfile
    image: python:3.11
    container_name: python_app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: bash -c "while true; do sleep 1000; done"  # Keeps the container running
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: filmpoint
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
